# Generated by Django 6.0.6 on 2026-06-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(verbose_name='описание')),
                ('status', models.CharField(choices=[('new', 'новая'), ('in_progress', 'в работе'), ('closed', 'закрыта')], default='new', max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'db_table': 'requests',
            },
        ),
    ]
